[package]
name = "eigenix-web"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
wasm-bindgen = "=0.2.104"
dioxus = { version = "0.7.0-rc.3", features = ["web"] }
serde.workspace = true
serde_json.workspace = true
web-sys = { version = "=0.3.81", features = ["Window", "Storage"] }

[features]
default = ["web"]
web = []
desktop = []
mobile = []
