[application]
name = "eigenix-web"
default_platform = "web"

[web.app]
title = "Eigenix"

[web.watcher]

[web.server]
addr = "0.0.0.0"
port = 8080

[bundler]

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files - ECharts required for Charming
script = [
  "https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js"
]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
