[application]
name = "eigenix-web"
default_platform = "web"

[web.app]
title = "Eigenix"

[web.watcher]

[web.server]
addr = "0.0.0.0"
port = 9090

[bundler]

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
